### ISSUE TITLE
Cajanus_cajan genome/annotation files 

### ISSUE THREAD

**Issue by jd-campbell** [LegumeFederation/datastore#14]
**DUE: November 24th, 2017**
Cajanus_cajan (pigeonpea) genome/annotation files need to be worked on. 

- [x] 1. Genome directory and annotation directory need a key 
- [ ] 2. Metadata files need to be started (paper reference? people assisted w/ project so I can list)
- [ ] 3. Rename files to data store standards
- [ ] 4. Transfer to public

**Comment by adf-ncgr** [comment]
Hi Jacqueline-
nice use of tasklist notation- I think you've become a githubmaster already.

one thing I'd like to discuss before we go too far with pigeonpea; there exists a DOI for the genome+annotation 
http://dx.doi.org/10.5524/100028
resolving to
http://gigadb.org/dataset/100028

I think what is in the datastore corresponds to:
http://www.ceg.icrisat.org/gt-bt/iipg/genomedata.zip
(linked from http://www.ceg.icrisat.org/gt-bt/iipg/Genome_Manuscript.html which is actually used in the manuscript)
this has both the subfolders 2.2 gene_total and 2.3 gene_TEs_excluded (as well as
the others); I think when chado was loaded we probably took "gene_total" whereas the browser team probably loaded the gffs in 2.3_gene_TEs_excluded as separate tracks. 
2.2_gene_total/Pigeonpea_gene.gff:48680
2.3_gene_TEs_excluded/Pigeonpea.gff.TE.gff:8609
2.3_gene_TEs_excluded/Pigeonpea.gff.filterTE.gff:40071

using the filtered version seems like the appropriate thing to do, but explaining the provenance of all this seems a bit challenging. anyway, just wanted to get this on your radar as what I think we meant in terms of "rationalizing" the chado-datastore representations in that agenda item.

**Comment by adf-ncgr** [comment]
OK, in order to help get this process moving (and also to facilitate @sdash-github work to get a cajca gene atlas in place before my ICRISAT trip), I have assigned "keys" and created an AHRD-ified version of 2.3_gene_TEs_excluded/Pigeonpea.gff.filterTE.gff following the current standards for naming (ie with datastore-derived prefixes for unique naming) and following the proposal outlined in RFO #17. In the absence of Objections early next week, I will press forward with retrofitting our chado to reflect the contents of this file.

**Comment by adf-ncgr** [comment]
Issue moved to [LegumeFederation/datastore-temp_mv_to_lf #3](https://github.com/LegumeFederation/datastore-temp_mv_to_lf/issues/3) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sdash-github** [comment]
My notes during atlas data processing mention this:
"
20171106:
----------------------------NEW GFF from ADF
Per ADF's recc using the following build and gff:
build:
data/private/Cajanus_cajan/ICPL87119.gnm1.SBGP/Pigeonpea.scafSeq.LG.fa
gff:
/usr/local/www/data/private/Cajanus_cajan/ICPL87119.gnm1.ann1.Y27M/cajca.ICPL87119.gnm1.ann1.AHRD.gff3.gz"

Now I see that this file, of course, has been renamed with 
"gene_models_main" string added to make it confirm to our recently 
adopted DS convention.
Let me know if you have questions

Sudhansu

**Comment by sdash-github** [comment]
My notes during atlas data processing mention this:
"
20171106:
----------------------------NEW GFF from ADF
Per ADF's recc using the following build and gff:
build:
data/private/Cajanus_cajan/ICPL87119.gnm1.SBGP/Pigeonpea.scafSeq.LG.fa
gff:
/usr/local/www/data/private/Cajanus_cajan/ICPL87119.gnm1.ann1.Y27M/cajca.ICPL87119.gnm1.ann1.AHRD.gff3.gz"

Now I see that this file, of course, has been renamed with 
"gene_models_main" string added to make it confirm to our recently 
adopted DS convention.
Let me know if you have questions

Sudhansu
