### ISSUE TITLE
Change all GFF fils to *.gff3 extension

### ISSUE THREAD

**Issue by jd-campbell** [LegumeFederation/datastore#16]
Which file extension do we want to use? 
```
cd /usr/local/www/data/public
ls */*/*.gff*gz | perl -pe 's/.+\.([^.]+)\.[^.]+$/$1\n/' | sort | uniq -c | sort -n 
 31 gff3
 64 gff
```

**Comment by adf-ncgr** [comment]
FWIW, the comment associated with commit 7497695 suggests that we officially decided on gff3
as does this section of about_the_data_repository.md 
Use consistent suffixes:
faa - protein FASTA
fna - nucleotide FASTA
gff3 - GFF
md - README files
tsv - ascii table file
txt - ascii files other than READMEs

I think many if not all of the synteny files are still using the gff suffix and should probably be made to conform. Does Wei have a github account? Not seeing her listed in LegFed organization or I might add her to the assignment list here.

**Comment by ekcannon** [comment]
I don't have strong feelings on the matter. "gff3" is more explicit, so that is fine with me.

**Comment by cann0010** [comment]
Agreed.

**Comment by adf-ncgr** [comment]
Issue moved to [LegumeFederation/datastore-temp_mv_to_lf #4](https://github.com/LegumeFederation/datastore-temp_mv_to_lf/issues/4) via [**ZenHub**](https://www.zenhub.com/)
