### ISSUE TITLE
RFO: handling of gff files that don't contain explicit entries for genes (but do contain mRNAs)

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/datastore#17]
This comes up from time to time for annotation files that we obtain from other groups. Typically, the absence of gene records implies that no attempt has been made to assess alternative splicing and often the transcripts contain no UTRs. For many of our purposes, we need to ensure that we have explicit representation of genes so we will add them to the gff file, using the boundaries of each mRNA as the boundaries of the gene and associating the mRNA with the gene as its Parent. For the Naming/IDentification of the newly created gene entries, we have been somewhat inconsistent in the past, sometimes adding a _gene suffix to make a clearer distinction. Given our recent decision that peptides SHALL have the same name as the transcripts from which they are derived, a similar principle seems to operate here and in this 1:1 relation between mRNAs and the genes inferred from them we PROPOSE that the genes use the same naming as the given mRNAs.
In the absence of stated opposition from federation partners, this rule will go into effect and we will undertake to make previously imported datasets consistent as time permits.

**Comment by adf-ncgr** [comment]
Hmm, I think I need to raise the first objection to my own RFO. At least in the context of the gff we can't have a gene and its mRNA using the same ID, although the chado into which it would be loaded would be happy to have the two present with the same uniquename (since the uniqueness constraint includes type_id). I guess the reason this doesn't come up with transcripts and polypeptides is that the polypeptide doesn't typically appear explicitly in the gff, it is inferred from the CDS features. 

I suppose an alternative would be to create a gene and transfer the identity of the mRNA to it, and just use the typical "suffix .1" to handle re-naming the mRNA. Probably as reasonable as anything else we are likely to come up with, though one could certainly argue that making our dataloaders dictate our standards is a bad idea. 

Note that if we adopt this modified proposal, and rename some of our transcripts (which implies renaming the associated peptides thanks to the decision we made earlier about that), it may well require a little retrofitting of the new gene family datafiles (which is not a new problem, so we have scripts to address it if required).

**Comment by adf-ncgr** [comment]
Note that I just made a "working implementation" of this proposal for cajca.ICPL87119.gnm1.ann1.AHRD.gff3.gz

since pigeonpea needed to have some work done on the chado representation anyway (demoting the TEs that had been imported as genes early on), this seemed like a reasonable time to implement a change, though I will hold off on actually messing with chado until the BIC/NAPIA group have had time to issue objections.

**Comment by sammyjava** [comment]
I do NOT Object to the .1 uniqueification of the mRNA name. I think it's a fairly standard practice.
