### ISSUE TITLE
RFO: put md5sums in dedicated file, rather than in READMEs

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/datastore#19]
per discussion in today's legfed meeting, it was agreed (and without objection, so I'm not really
requesting any retrospectively!) that instead of putting md5 checksums for files maintained in the datastore into the folder README files, that each folder would just have a file that contains the md5sums for all the files in the folder (as is pretty standard, so that md5sum -c list_file will do all the checks for you). Once someone has written this into the master doc to commemorate the decision, it can be closed (though someone will still have to actually do it for the datastore folders as well).

**Comment by adf-ncgr** [comment]
OK, about to get this one documented in the master datastore file in prep for closing;
have made the executive decision that this file will be named using the same prefixing as the standard prefixing associated with the folder and will have a suffix of .md5sum (.md5 looking to me uncomfortably similar to .md which is being used as the markdown suffix for the READMEs).
Also, have made the decision that we will follow GNU md5sum format expectations, which on BSD systems (like what lis- servers are using) can be obtained as, e.g.:
/usr/local/www/data/public/Lupinus_angustifolius/Tanjil.gnm1.Qq0N
md5 -r * > lupan.Tanjil.gnm1.Qq0N.md5sum

verified that this comes out cleanly on a Linux system as: 
md5sum -c lupan.Tanjil.gnm1.Qq0N.md5sum
README.Qq0N.md: OK
lupan.Tanjil.gnm1.Qq0N.genome_main.fna.gz: OK
lupan.Tanjil.gnm1.Qq0N.pschrom.fna.gz: OK
lupan.Tanjil.gnm1.Qq0N.scaf.fna.gz: OK
lupan.Tanjil.gnm1.Qq0N.scaf_unassigned.fna.gz: OK
original_readme.lupinexpress.txt: OK

anyone watching has until I get this typed into the master datastore README file to Object or hold your peace until you can get the 7/8 majority needed to get an amendment :)

**Comment by cann0010** [comment]
After some side-discussions (ADF, SC), we see a problem with the lupan.Tanjil.gnm1.Qq0N.md5sum form:  it visually buries the md5 file amongst the data – whereas the other metadata files (README, MANIFEST) have a naming form that suggests that they aren’t primary data.

So instead, we propose the form MD5.KEYNAME - for example,
MANIFEST.FCtY.correspondence
MANIFEST.FCtY.descriptions
MD5.FCtY
README.FCtY.md
glyma.Wm82.gnm1.FCtY.genome_main.fna.gz
glyma.Wm82.gnm1.FCtY.hardmasked.fna.gz
glyma.Wm82.gnm1.FCtY.softmasked.fna.gz

**Comment by adf-ncgr** [comment]
woohoo
