### ISSUE TITLE
should we get a consistent convention going for having a fasta for "a genome"

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/datastore#2]
@cann0010 
"NCBI uses a _genomic.fna suffix for genome assembly (as well as a fairly complex directory hierarchy for assembly components and tiling path, etc.). We are using a hybrid naming system, with _pchr.fna for pseudochromosomes and _scaf.fna for scaffolds."

I strongly feel that we should have at least one file that contains "the genome" in the sense of a non-redundant but as-put-together-as-possible version (in general would contain pseudochromosomes and unplaced scaffolds). I am somewhat agnostic on whether or not we want to also supply files that separate stuff out into specialized bins, but I think in general users want a single file that has it all (non-redundantly). I observe that whatever the bullet may intend, we don't follow it very faithfully in practice and we probably ought to get a solid naming convention established:

```
[adf@lis-stage /usr/local/www/data/public]$ find . -path "*gnm[0-9]*"  | egrep 'fna.gz|fa.gz|fasta.gz' | grep -v cds | grep -v protein | grep -v pep | grep -v masked | grep -vi transcript
./Glycine_max/Williams82.gnm1.FCtY/glyma.Wm82.gnm1.FCtY.fa.gz
./Vigna_radiata/VC1973A.gnm6.3nL8/vigra.VC1973A.gnm6.3nL8.pchr_plus_unassigned.fna.gz
./Vigna_angularis/Gyeongwon.gnm3.JyYC/vigan.Gyeongwon.gnm3.JyYC.pchr_plus_unanchored.fna.gz
./Trifolium_pratense/MilvusB.gnm2.gNmT/tripr.MilvusB.gnm2.gNmT.pchr_plus_unanchored.fna.gz
./Lupinus_angustifolius/Tanjil.gnm1.Qq0N/lupan.Tanjil.gnm1.Qq0N.pchr.fna.gz
./Lupinus_angustifolius/Tanjil.gnm1.Qq0N/lupan.Tanjil.gnm1.Qq0N.scaf_unassigned.fna.gz
./Lupinus_angustifolius/Tanjil.gnm1.Qq0N/lupan.Tanjil.gnm1.Qq0N.scaf.fna.gz
./Phaseolus_vulgaris/G19833.gnm2.fC0g/phavu.G19833.gnm2.fC0g.fa.gz
./Phaseolus_vulgaris/G19833.gnm1.zBnF/phavu.G19833.gnm1.zBnF.fa.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B08.gnm1.bXJ8.chr.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B03.gnm1.bXJ8.chr.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B10.gnm1.bXJ8.chr.by_scaff.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B06.gnm1.bXJ8.chr.by_scaff_RM.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B02.gnm1.bXJ8.chr.by_scaff_RM.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B07.gnm1.bXJ8.chr.by_scaff.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B01.gnm1.bXJ8.chr.by_scaff.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B05.gnm1.bXJ8.chr.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B02.gnm1.bXJ8.chr.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B_unplaced.gnm1.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B09.gnm1.bXJ8.chr.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B03.gnm1.bXJ8.chr.by_scaff_RM.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B06.gnm1.bXJ8.chr.by_scaff.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B04.gnm1.bXJ8.chr.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B10.gnm1.bXJ8.chr.by_scaff_RM.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B07.gnm1.bXJ8.chr.by_scaff_RM.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B08.gnm1.bXJ8.chr.by_scaff_RM.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B01.gnm1.bXJ8.chr.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.pchr_20140908.gnm1.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B09.gnm1.bXJ8.chr.by_scaff.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B10.gnm1.bXJ8.chr.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B01.gnm1.bXJ8.chr.by_scaff_RM.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B05.gnm1.bXJ8.chr.by_scaff.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B07.gnm1.bXJ8.chr.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B05.gnm1.bXJ8.chr.by_scaff_RM.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B03.gnm1.bXJ8.chr.by_scaff.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B04.gnm1.bXJ8.chr.by_scaff_RM.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B08.gnm1.bXJ8.chr.by_scaff.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B06.gnm1.bXJ8.chr.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B04.gnm1.bXJ8.chr.by_scaff.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B02.gnm1.bXJ8.chr.by_scaff.fna.gz
./Arachis_ipaensis/K30076.gnm1.bXJ8/araip.K30076.B09.gnm1.bXJ8.chr.by_scaff_RM.fna.gz
./Cicer_arietinum/ICC4958.gnm2.bg5m/cicar.ICC4958.gnm2.bg5m.fa.gz
./Cicer_arietinum/CDCFrontier.gnm1.GkHc/cicar.CDCFrontier.gnm1.GkHc.fa.gz
```

**Comment by adf-ncgr** [comment]
another point to be determined on this issue; do we leave sequence names unaltered from their source, use "browser-friendly" or "chado-friendly" naming (or provide a file for each, or a lookup table or?)

**Comment by vivekkrish** [comment]
Hi @adf-ncgr,

I would vote for the latter - provide a lookup table which maps the reference sequence IDs in the GFF3/FASTA file (genome-browser-friendly) to the corresponding identifiers in the database (Chado-friendly). This implementation would be similar to the data file provided by NCBI GenBank via their FTP, for example: [GCA_002024945.1_R108_v._1.0_assembly_report.txt](ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/002/024/945/GCA_002024945.1_R108_v._1.0/GCA_002024945.1_R108_v._1.0_assembly_report.txt).

Such an approach obviously puts the onus on the downstream consumer to be responsible for parsing/modifying the files according to their needs.

Would love to hear your (and others) thoughts on this or any other alternate mechanisms.

Thank you!

P.S. I'm not sure if everyone on the LegFed group gets notified when issues are created or posted (unless they are explicitly "Watching" a certain repo, or they get tagged in the comment). Should we think about bulk-adding the entire LegFed core team to repos with broad topics like the datastore?

**Comment by cann0010** [comment]
I like this suggestion (a lookup table). This could be done in the Data Store: a lookup table for the assembly and one for the annotations, in each of the respective data collections.

sc

**Comment by adf-ncgr** [comment]
Thanks, both (I think all repository watchers and @mentions will get this, but @vivekkrish is probably right that we should conscript some people to participate)-
NCBI precedents are always nice to follow. In their case, the actual fasta uses the accession numbers they assign as the primary id in the fasta header, and retains the submitters naming as secondary:
>MWMB01000001.1 Medicago truncatula isolate HM340 scf000, whole genome shotgun sequence

This could be argued to imply that our fastas should have legfed-unique identifiers as primary and
original or alternative naming would be lookup-able. This would facilitate downstream users being able to "aggregate" our files and not have to worry about naming collisions (ie "which scf000 was this one?")

I'm not wedded to this interpretation of what it would mean to follow the NCBI implementation, but thought I would volunteer it as a possibility that is arguably most useful to our customers. The only sensible alternative I see would be saying that original naming stays as is in these files. There's a certain lazy charm to that solution as well...

**Comment by adf-ncgr** [comment]
per discussion with legfed group today, and parallel to #18 it was decided that we will have files representing "the genome" to match with the canonical annotation file (ie the sequence identifiers in the fasta will match what is found in column1 of corresponding gff3 files, though this should not be construed to preclude the possibility that some sequences in the fasta will not have annotations- it just means that the naming conventions will be the same between the two). As our exemplar name for a canonical annotation file was "cajca.ICPL87119.gnm1.ann1.canonical.gff3.gz" so its corresponding genomic fasta would be "cajca.ICPL87119.gnm1.canonical.fna.gz" (and of course it would be found in the appropriate folder, namely Cajanus_cajan/ICPL87119.gnm1.KEYX (NB, I am being lazy and not checking what is the actual assigned value of KEYX).

**Comment by cann0010** [comment]
Delayed response ... but I've got to object to use of "canonical" to indicate the primary genome assembly. The term is an adjective that needs to describe something else - like "main_genome." I think in most of our assembly directories, we will have only one fasta file for the assembly (other files will be tarred directories of files-per-pseudomolecule etc., or AGP files etc.; Arachis ipaensis and Arachis duranensis are bad examples that need to be fixed). 

So if it is correct that we will have only one fasta file for the assembly, I think then we don't need to apply the adjective. Instead, just use this form: glyso.PI483463.gnm1.YJWS.main_genome.fna . This is close to what the Hudson-Alpha group uses for all of their assemblies: "mainGenome." 

For example, here is the file-set for a new assembly that I'm working on, with the descriptive suffixes that I would like to use. The last three are tarred directories.
glyso.PI483463.gnm1.YJWS.agp.gz
glyso.PI483463.gnm1.YJWS.main_genome.fna.gz
glyso.PI483463.gnm1.YJWS.pchr_by_scaff.tar.gz
glyso.PI483463.gnm1.YJWS.pchr_entire.tar.gz
glyso.PI483463.gnm1.YJWS.scaffolds_split.tar.gz

**Comment by adf-ncgr** [comment]
I don't have strong opinions about it as long as we are consistent; part of the thinking was to use a common tag like "canonical" across different data types (e.g. genome assemblies and genome annotations) to indicate the resource that we consider to be the best representation for general downstream use. @cann0010 do you wish to propose something other than "canonical" for the annotation file that is to be considered "the one to use" (which might be distinguished from the original gff that we've done some cleaning on, or from the gff that contains TEs among its genes, etc. etc.)

**Comment by ekcannon** [comment]
The term settled on by MaizeGDB, following GenBank's lead, is "representative". We wanted to use "reference" but now have several reference-quality maize genomes.

**Comment by cann0010** [comment]
@adf-ncgr, @ekcannon - for genome assemblies, I propose simply "**main_genome**", with the filename taking this form: gensp.Accession.gnm#.KEYX.main_genome.fna

There might be other tar.gz'd directories with related assembly parts (multifasta pseudomolecules by scaffold, repeat masked assemblies, etc.). Other assembly versions should go in other keyed, main-level directories. But I think we (and others) will see **main_genome.fna** as the one to focus on.

As for how to identify which of THOSE is recommended as the representative assembly, I am not sure. For example, we have a Glycine_max.Williams82.gnm1.FCtY/ and a Glycine_max/Williams82.gnm2.DTC4/ ... and we recommend gnm2 ... but people are free to use either. Presumably they would pick the latest version if they have the choice.

**Comment by adf-ncgr** [comment]
Not %100 sure, but I think we're talking about two different things. Isn't "representative" the way that they (NCBI) indicate which genome is to be preferred (for whatever reason) among those which may be available for a species? My intent with this thread is just about indicating which file in a given "gnm" folder is to be considered the best choice as a representation for downstream use (assuming someone has already decided they want to use the genome) among other fasta files (if any) in that folder.

**Comment by cann0010** [comment]
Incidentally, I have fixed the _Arachis duranensis_ and _Arachis ipaensis_ collections to my liking. (I guess this is implicitly a RFO)
https://legumeinfo.org/data/public/Arachis_duranensis/V14167.gnm1.SWBf/
https://legumeinfo.org/data/public/Arachis_ipaensis/K30076.gnm1.bXJ8/
