### ISSUE TITLE
versioning info in master README 

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/datastore#20]
The current file about_the_data_repository.md contains authorship and date info:
Steven Cannon Revision: 2017-07-19

Do we want the latter to be automatically updated when new changes are committed (relatively easy to do using git mechanisms I think). Do we want to extend co-authorship (read: shared responsibility) to others in the federation (assuming this is to be understood as a federation charter and not LIS-specific document)? @cann0010 your call as first author...

**Comment by cann0010** [comment]
That was a relic from my initial ad hoc private versioning habit. I've removed the author and date line.
