### ISSUE TITLE
bgzip and tabix index relevant files

### ISSUE THREAD

**Issue by nathanweeks** [LegumeFederation/datastore#22]
bgzip compression and tabix indexing can be used to allow random access over HTTP(S) to relevant data files for supporting applications (e.g., JBrowse).

For GFF3, sort/validate before bgzip / tabix as per https://github.com/LegumeFederation/datastore/issues/6#issuecomment-348627463,

Protocols for other file formats?

**Comment by vivekkrish** [comment]
Hi @nathanweeks,

I've written up some generic documentation/protocol for prepping different data file formats to support HTTP Range access. It's available on the Araport GitHub wiki: https://github.com/Arabidopsis-Information-Portal/jbrowse-tabix-howto/wiki

There are some caveats, however, with GFF3 tabix indexing. The sorting that `genometools` does isn't compatible with tabix, and thus requires either the use of unix `sort` or an alternative approach, such as the one implemented here: https://github.com/billzt/gff3sort

For all other file formats (BAM, BED, VCF and bigWig), it's pretty straightforward to sort, compress and index.

Thank you!

**Comment by nathanweeks** [comment]
Thanks @vivekkrish , that's good information. I had only tried tabix indexing a file sorted with ```gt gff3 -sort``` that contained expressed_sequence_match features, not gene features with a parent/child relationship.

**Comment by adf-ncgr** [comment]
basically agreed to. for genome fastas and gffs
