### ISSUE TITLE
Proposal for elements for human-readable portions of filenames

### ISSUE THREAD

**Issue by cann0010** [LegumeFederation/datastore#23]
I propose the following patterns for the terminal human-readable portions of the Data Store filenames.

### The human-readable portion of the filename should be:
  - Brief
  - Use snake_case (with a few established exceptions)
  - Not include periods within the human-readable portion
  - More important elements come first within the descriptor: 
    - "cds" before "_primaryTranscript"
    - "gene_models" before "_by_scaff"
  - The main annotation file is marked with "_main":
    - gene_models_main.gff3
  - The main assembly file is marked with "_main":
    - genome_main.fna
  - We maintain a core set of files. Some annotation or assembly sets 
    may have additional files that are kept off to the side, unmodified, in a subdirectory.

== Suffixes:
  - Fasta - nucleotide: .fna
  - Fasta - protein: .faa
  - Coordinates: .gff3 if file validates as gff3
                 .gff if file is essentially gff but doesn't validate as gff3
  - Other information files (lists, tables): .txt

### Annotation files and suffixes
```
  - CDS sequence files
    - cds                             fna
    - cds_primaryTranscript           fna

  - Protein sequence files
    - protein                         faa
    - protein_primaryTranscript       faa

  - Transcript sequence files
    - transcript                      fna
    - transcript_primaryTranscript    fna

  - Gene models. The "main" GFF file is so-labeled
        Suffixes: gff3 if the file validates as gff3, else gff
    - gene_models_main                gff or gff3
    - repeats                         gff or gff3; e.g. output of RepeatMasker
    - Some "non-main" variants may be included (e.g. gene_models_mRNA), but generally, 
      keep "other stuff" off to the side, in a subdirectory "originals_and_extras"

  - Additional information: synonyms, lists, etc.
    - info_repeats                    txt
    - info_annot                      txt
    - info_annot_InterPro             txt
    - info_annot_etc                  txt

  - Coordinates for non-genic features: scaffolds, centromeres, etc.
    - scaffold_coords                 gff or gff3
```

### Assembly files and suffixes
```
  - Main assembly, with pseudomolecules + remaining scaffolds
    - genome_main                     fna
  
  - Pseudomolecules or unanchored scaffolds in multifasta pieces
    - pchr_by_scaff                   fna
    - scaff_unassigned                fna
```

**Comment by ctcncgr** [comment]
Following up briefly after todays meeting.

I went and looked at several genomes in ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/plant/ and all of them have fna for the primary assembly and have faa when amino acid sequences are available.

According to https://www.ncbi.nlm.nih.gov/genome/doc/ftpfaq/#files, it seems to me that fna and faa are still being used and I wasn't able to find anything about that changing (if anyone has information to the contrary please post it).

Historically I have seen a lot of fna and faa fies, but not a lot of the other extensions outside of NCBI, and it seems like fna and faa are predominant these days on the NCBI FTP site as well.  This may reflect a general migration towards simplifying the suffixes, which is probably a good thing.  There are many examples in FASTA of extensions being abandoned (seq, fsa, mpfa, etc...) for the simple fasta or fa.  Also many other groups do not seem to adhere to these extensions, so perhaps they aren't of much value as long as its clear what you are looking at.

Primarily my reasoning is for fna and faa files, where I have found it useful when browsing through files to be able to clearly see which files are amino acid and which are not, without having to download them and less them to check.  If we are consistent with our naming conventions this may not be a concern.

Anyway, whatever is decided is certainly fine with me as long as we are consistent :)

**Comment by sammyjava** [comment]
As a new consumer of datastore files (mine builds) I say all that matters tome is consistency.

**Comment by cann0010** [comment]
Thanks for checking, Connor. Looking at a selection of assembly and annotation FTPcollections in GenBank (beet, tomato, banana), I see the same thing: .fna, .faa for nucleotide and amino acid, respectively. Selected examples from beet:
GCA_000511025.2_RefBeet-1.2.2_cds_from_genomic.fna.gz
GCA_000511025.2_RefBeet-1.2.2_genomic.fna.gz
GCA_000511025.2_RefBeet-1.2.2_rna_from_genomic.fna.gz

GCA_000511025.2_RefBeet-1.2.2_genomic.gff.gz

GCA_000511025.2_RefBeet-1.2.2_protein.faa.gz
GCA_000511025.2_RefBeet-1.2.2_translated_cds.faa.gz

So I think I revert my suggestion to simplify to .fa. Rather, stay the course with .fna and .faa.

**Comment by sammyjava** [comment]
True dat, but I'll point out that Ensembl Plants, which is where I get my non-legume genomes, uses .fa for everything. But using GenBank as a standard is as good as any. From the README (for Zea mays or anything, goofy that they use the human example):
```
EXAMPLES
   The genomic sequence of human chromosome 1:
     Homo_sapiens.GRCh37.dna.chromosome.1.fa.gz

   The masked version of the genome sequence on human chromosome 1
   (contains '_rm' or '_sm' in the name):
     Homo_sapiens.GRCh37.dna_rm.chromosome.1.fa.gz
     Homo_sapiens.GRCh37.dna_sm.chromosome.1.fa.gz

   Non-chromosomal assembly sequences:
   e.g. mitochondrial genome, sequence contigs not yet mapped on chromosomes
     Homo_sapiens.GRCh37.dna.nonchromosomal.fa.gz
     Homo_sapiens.GRCh37.dna_rm.nonchromosomal.fa.gz
     Homo_sapiens.GRCh37.dna_sm.nonchromosomal.fa.gz
```

**Comment by adf-ncgr** [comment]
I don't think this is closed yet. I agree with sticking to fna/faa but this decision is only one facet and I think we shouldn't close it until the master README for the datastore reflects whatever agreement we have reached about at least the key files for gnm and ann datasets.

**Comment by sammyjava** [comment]
^^^^^^ He's tough!

**Comment by cann0010** [comment]
OK - I've updated the RFO document at the top of the thread. Main changes:
- Fasta: stick with our status quo of .fna and .faa (not .fa)
- Added a principle:  "We maintain a core set of files. Some annotation or assembly sets 
    may have additional files that are kept off to the side, unmodified, in a subdirectory."
   ... and, under Gene models, I added: "Some "non-main" variants may be included 
      (e.g. gene_models_mRNA), but generally, keep "other stuff" off to the side, 
      in a subdirectory "originals_and_extras" " ***
- Removed genome_hardmasked from the Assembly files section, because repeat features can be indicated with GFFs - which a user can use to mask a genome with bedtools etc.

*** Note about this: "keep "other stuff" off to the side, in a subdirectory "originals_and_extras" " - There are some details to work out about this. Do we keep all files in their original forms? For data collections that we have already prepared, do we move "extra" stuff off into this annex directory? In that case, they are not "originals," because we have renamed them - and sometimes transformed them. Probably a topic for a new thread.

**Comment by adf-ncgr** [comment]
It's looking good to me! The main residual thing I'd like to see a bit more clarity on is the distinction between specifically what we would consider to be required vs what can be considered "extra" (regardless of whether we choose to place the extras to a subfolder or just let them be ignored by programs that don't care about them);
e.g. it's not a real gnm (TM) if it doesn't have a  
<gensp>.<geno>.<gnmX>.<key>.genome_main.fna.gz file 
it's not a real gnm.ann (pat pending) if it doesn't have 
<gensp>.<geno>.<gnmX>.<annY>.<key>.gene_models_main.gff3.gz file;
and I think also we've essentially agreed on the derived faa and fna files discussed in #1, but I don't think we've agreed that it has to have an explicit repeats or scaffold_coords to qualify as gnm.ann, though if it does have them they SHALL conform to the naming prescribed.

there will likely be some dataset types where we'll need to evolve our concept for what is the "Minimal Information About This Type", but it seems like we may be reaching agreement on this for gnm and gnm.ann and I think that would be a great way to begin 2018:
with YAMOP- yet another month of pain; but hopefully the last we'll need for gnm and gnm.ann...

**Comment by adf-ncgr** [comment]
per discussion in today's legfed group call, I will document details pertaining to our agreement to use "yucky naming" for entities within genome_main and gene_models_main files.

**Comment by cann0010** [comment]
Continuing this discussion, on the topic of the ""yucky naming" for entities within genome_main and gene_models_main files":
Taking the cases of two new soybean assemblies, Glycine soja PI483463 and Glycine max Lee:
  glyso.PI483463.gnm1.YJWS.genome_main.fna
  glyma.Lee.gnm1.BXNC.genome_main.fna
The entities within these assemblies are pseudomolecules and scaffolds:
```
  >Gs01
  >Gs.sc255 
```
and 
```
  >Gm01 
  >Lee.sc457
```
Should we ...
(1) Prefix them:
```
  >glyso.PI483463.gnm1.YJWS.Gs01
  >glyso.PI483463.gnm1.YJWS.Gs.sc255 
```
(2) Provide a "fully-qualified" name as an alias:
```
  >Gs01 glyso.PI483463.gnm1.YJWS.Gs01
  >Gs.sc255 glyso.PI483463.gnm1.YJWS.Gs.sc255 
```
(3) Something else - e.g. postfix with the ugly portion?

And ... include the key name (YJWS) or not?

Assuredly, the first option (1) will be unpopular with some users and curators.

Here is one context in which the named elements will be seen:
https://legumeinfo.org/genomes/gbrowse/vigun.IT97K-499-35.gnm1

The assemblies were been submitted to GenBank in December, using the short reference names:
https://www.ncbi.nlm.nih.gov/nuccore/PGFP00000000
https://www.ncbi.nlm.nih.gov/gquery/?term=PELE00000000

**Comment by adf-ncgr** [comment]
no longer contentious...
