### ISSUE TITLE
RFO: put file lists in dedicated manifest files, rather than in READMEs

### ISSUE THREAD

**Issue by cann0010** [LegumeFederation/datastore#25]
To help regularize the Data Store metadata and make it more machine-readable, I propose pulling the file lists (file descriptions and file provenance) out of the main README file and into two MANIFEST files, with the naming form. The content has a "#"-anchored comment line. The first field has the data file names in the Data Store. In the correspondence file, the second field has the preceding name (if any). In the descriptions file, the second field (following the first whitespace delimiter) has the file descriptions.
 
cat MANIFEST.FCtY.correspondence
#filename in this repository              previous name
glyma.Wm82.gnm1.FCtY.main_genomefna.gz    Gmax_189.fa.gz
glyma.Wm82.gnm1.FCtY.hardmasked.fna.gz    Gmax_189_hardmasked.fa.gz
glyma.Wm82.gnm1.FCtY.softmasked.fna.gz    Gmax_189_softmasked.fa.gz

cat MANIFEST.FCtY.descriptions
#filename in this repository              description
glyma.Wm82.gnm1.FCtY.main_genomefna.gz    Genome assembly
glyma.Wm82.gnm1.FCtY.hardmasked.fna.gz    Genome assembly: masked with 'N's
glyma.Wm82.gnm1.FCtY.softmasked.fna.gz    Genome assembly: masked with lowercase

**Comment by adf-ncgr** [comment]
no objection here. examples seem to be missing a '.' between main_genome and fna.
you should probably provide an example of the case where a main_genome file has been
composed of multiple source files (e.g. I think in lupan.Tanjil.gnm1 we cat'd pseudchr and unplaced scaffolds)

**Comment by adf-ncgr** [comment]
agreed
