### ISSUE TITLE
misplaced folder and permissions need adjusting globally

### ISSUE THREAD

**Issue by adf-ncgr** [LegumeFederation/datastore#3]
@cann0010 - in the cyverse datastore the folder mixed.map1.blair.7PMp is at the level of the species folders, whereas it looks like it is meant to be under Phaseolus_vulgaris (ie it is there in the legumeinfo data area). I was going to fix it, but it looks like the permissions on the Legume_Federation folder in cyverse have reverted to you owning them with no one else in the group having write access- looks like this is something that will need to get handled in the protocol for updating the datastore (unless we think it's appropriate that way).
```
/iplant/home/shared/Legume_Federation:
        ACL - g:public#iplant:read object   cannon#iplant:own   g:rodsadmin#iplant:own   anonymous#iplant:read object   ipc_admin#iplant:own
        Inheritance - Enabled
```

**Comment by cann0010** [comment]
Thanks for the catch, Andrew.

I’ve moved the Blair marker dataset into the correct spot.
http://datacommons.cyverse.org/browse/iplant/home/shared/Legume_Federation/Phaseolus_vulgaris/

Eric (or anyone else who knows the answer): how to add group-write permissions to files or directories? The syntax appears to be different from the unix chmod that I am familiar with … judging by this documentation:  https://pods.iplantcollaborative.org/wiki/display/DS/Using+iCommands
… and from ichmod -h

ichmod write Group *
ERROR: rcModAccessControl failure  status = -816000 CAT_INVALID_ARGUMENT
ERROR: Level 0: Input path is not a collection and not a dataObj: /iplant/home/shared/Legume_Federation/Phaseolus_vulgaris/mixed.map1.blair.7PMp/G19833.gnm1.ann1.pScz

sc

**Comment by adf-ncgr** [comment]
@cann0010 - thanks for the fix on the folder location. I thought I had remembered that we all belonged to an irods group added for the legfed project, but either I am mistaken or not understanding how to get the group name:
iuserinfo adf
name: adf
id: 2189447
type: rodsuser
zone: iplant
info:
comment:
create time: 01310058936: 2011-07-07.11:15:36
modify time: 01310058936: 2011-07-07.11:15:36
member of group: adf
member of group: public

I can try to dig up old emails about this and/or find out from cyverse staff what best path forward is....

**Comment by adf-ncgr** [comment]
OK, looking at my old emails from Jeremy deBarry it is not clear that we ever had a "group" but may have just done permissions at the level of individual users who were part of the project. Jeremy's note seems to suggest that doing things this way was a consequence of us not having come to an official decision for the project on how to manage permissions. Also, this page at cyverse seems to suggest that they think having a single PI manage the permissions is the preferred way: 
https://wiki.cyverse.org/wiki/display/DC/Using+CyVerse+for+a+Shared+Project
(see section "Managing data in a shared project" in particular). 

Probably worth some more group discussion, perhaps @elyons will have some additional perspective...

**Comment by jd-campbell** [comment]
@adf-ncgr @cann0010 Is this main issue "misplaced folder and permissions need adjusting globally" closed? 

Have we had the discussion with @elyons about manage the permissions in the CyVerse Data Store?

**Comment by adf-ncgr** [comment]
@jd-campbell no, we have not yet had this discussion with @elyons - for now I think @cann0010 remains the data master. so the misplaced folder has been resolved, but the broader issue of permissions management remains.

**Comment by adf-ncgr** [comment]
@amcooksey says maybe teams are being rolled out; we will look into trying it.

**Comment by amcooksey** [comment]
Here is the current situtation: 'Teams' have indeed been rolled out HOWEVER they only apply to apps an analyses at the moment. My understanding is that everyone wants 'Teams' for data but making it work with some of the iRODs rules is going to be a significant undertaking.

**Comment by adf-ncgr** [comment]
so is there a suggested plan B as far as how to deal with a situation like ours for the time being? To me, the simplest thing would be to have a dedicated account that has ownership and could simply be shared. I guess we all trust each other enough for this to work for the time being. Outside of trust issues, the main downside would seem to be loss of clear "accountability" (ie who was responsible for adding in particular resources to the shared space from their locally managed areas); again, we're a small enough group now that it doesn't seem a major concern. Open to other alternatives if others have better ideas.

**Comment by ekcannon** [comment]
One possibility, though it may be too late now, is to create a LegFed account to serve the whole team, and trusted members of the federation.

**Comment by cann0010** [comment]
Thank you Amanda.
I think we need a Legume Federation group, such that the group members have write permission at http://datacommons.cyverse.org/browse/iplant/home/shared/Legume_Federation

I don't have a list at-hand of the CyVerse user names for LegFed group members. I'll send an email, separately, asking people to send me their user names if they anticipate working in this space.

**Comment by adf-ncgr** [comment]
that sounds fine to me- I think most of us are interacting with the DS via icommands anyway.

**Comment by cann0010** [comment]
Amanda: we would like write access to the data commons shared/Legume_Federation directory for at least these users:
Jacqueline Campbell: jdjax
Connor Cameron:      ccameron
Ethy Cannon:          ecannon
Andrew Farmer:       adf
Steven Cannon:       cannon
Vivek Krishnakumar:  vivek
Medicago service account: mtruncatula

**Comment by amcooksey** [comment]
According to Tony we now have  a group: "Legume_Federation"

with these members (to start): 
Jacqueline Campbell: jdjax
Connor Cameron: ccameron
Ethy Cannon: ecannon
Andrew Farmer: adf
Steven Cannon: cannon
Vivek Krishnakumar: vivek
Medicago service account: mtruncatula
Sam Hokin: shokin

with write permissions here: http://datacommons.cyverse.org/browse/iplant/home/shared/Legume_Federation

**Comment by adf-ncgr** [comment]
Thanks! I think there may be a slight problem; I can write, don't have permission to remove what I wrote:
[adf@Macintosh:~:112]$ ipwd
/iplant/home/shared/Legume_Federation/Cajanus_cajan
[adf@Macintosh:~:109]$ imkdir quicktest
[adf@Macintosh:~:117]$ ils
/iplant/home/shared/Legume_Federation/Cajanus_cajan:
  C- /iplant/home/shared/Legume_Federation/Cajanus_cajan/ICPL87119.bac1.GpKx
  C- /iplant/home/shared/Legume_Federation/Cajanus_cajan/ICPL87119.gnm1.syn1.Nkx0
  C- /iplant/home/shared/Legume_Federation/Cajanus_cajan/mixed.mrk1.1drZ
  C- /iplant/home/shared/Legume_Federation/Cajanus_cajan/mixed.tcp1.mKS3
  C- /iplant/home/shared/Legume_Federation/Cajanus_cajan/quicktest

[adf@Macintosh:~:118]$ irm -r quicktest
ERROR: rmUtil: rm error for /iplant/home/shared/Legume_Federation/Cajanus_cajan/quicktest, status = -818000 status = -818000 CAT_NO_ACCESS_PERMISSION

I have a memory from long ago that there are some subtle and unexpected differences between the permissions associated with "modify" and "own", and it appears that this may be at play here:
ils -A
ACL - g:public#iplant:read object   cannon#iplant:own   anonymous#iplant:read object   g:Legume_Federation#iplant:modify object   g:rodsadmin#iplant:own

so maybe cannon#iplant (aka @cann0010 ) or the rodsadmin could undo my quicktest and we can discuss whether g:Legume_Federation#iplant:own would be more appropriate?
I'll try to dig up the details of when we ran into this before (way back in the Jeremy deBarry days of LegFed)

**Comment by amcooksey** [comment]
It seems to be an iRODs quirk. Here is what Tony has to say on the subject:
Oh that's right!  It's the Inheritance flag.  When inheritance is enabled, the inherited permissions override the normal ones.  
The good news is that he still is the creator of the collection, so he can give himself own permission of the collection.  `ichmod own adf quicktest`.  Then he can delete it/move it to trash.
I'll grant own permission to LegFed group

**Comment by adf-ncgr** [comment]
Oh thanks- FWIW, I found the old thread with Jeremy deBarry; in that case it was trying to rename a folder that had manifested itself as an operation that only an owner could do. Here's the permissions overview that Jeremy had found after consultation with the iRODS gurus
<img width="809" alt="datastore_permissions" src="https://user-images.githubusercontent.com/2009605/32642535-21e9f252-c592-11e7-8aba-7141f5d75bf7.png">

**Comment by adf-ncgr** [comment]
PS. Tony's suggestion worked like a charm...
