### ISSUE TITLE
Does it matter: GenBank or RefSeq assembly accession? 

### ISSUE THREAD

**Issue by jd-campbell** [LegumeFederation/datastore#37]
I may be splitting hairs here but I have noticed in some README files under #### GenBank Accession the actual accession posted is the RefSeq accession.  Does it matter which accession number is listed since either one will get the user to where they want to go? 

Example: Medicago_truncatula/A17_HM341.gnm4.ann2.G3ZY/README.G3ZY.md 
(Has the RefSeq accession listed: GenBank accession is GCA_000219495.2.) 
#### GenBank Accession
GCF_000219495.3

https://www.ncbi.nlm.nih.gov/assembly/GCF_000219495.3
![screen shot 2018-05-01 at 2 30 41 pm](https://user-images.githubusercontent.com/13021601/39489782-48744458-4d4c-11e8-92e9-d8d3dba38d64.png)

**Comment by cann0010** [comment]
If the question refers to the accession version (.1, .2, .3 etc.), then I think the safest course is to point to the accession without version any version (GCF_000219495) - which calls up all available versions.

**Comment by adf-ncgr** [comment]
The ability to split hairs is the mark of an up-and-coming ontologist :)

In this case, I think the NCBI description suggests that if we have included the chloroplast than we should use RefSeq otherwise we should use GenBank. I suspect the latter is true in this case.

FWIW, it might be a good idea for us to have a discussion about how to handle organelles. I personally think it is of interest to have them available in some form, though it does cause hair-raisingly hair-splitting opportunities for debate like this...

**Comment by jd-campbell** [comment]
@cann0010  The question refers to the **GCF_** or **GCA_** in front of the number. 
**GCF_** : RefSeq 
 **GCA_**: GenBank

**Comment by cann0010** [comment]
Ah, thanks. I didn't know the difference. Now I do (I think):
https://www.ncbi.nlm.nih.gov/books/NBK50679/#RefSeqFAQ.what_is_the_difference_between_1
It sounds like RefSeq is the better option when available.

**Comment by adf-ncgr** [comment]
Hang on; @cann0010 I think we should be clear on what the difference is between the RefSeq accession and the GenBank accession. In this case, I believe the primary differentiation is that RefSeq is considered to include the chloroplast, which is just "tacked on" from a much earlier project: https://www.ncbi.nlm.nih.gov/nuccore/AC093544 

In our genome fasta/annotation, we do not include the chloroplast. Therefore, I think it would be inappropriate to say that we have the RefSeq Genome (even though all the nuclear components are equivalent). Do you disagree?

**Comment by cann0010** [comment]
Ah - I had missed that detail. I was just judging by the description of the typical difference between RefSeq and GenBank accessions. I defer to you here.
As for whether we can make a general policy of favoring one form over another ... apparently not, unfortunately.

**Comment by cann0010** [comment]
And - @jd-campbell - no, I would say there is no need to review all readmes for this technicality. Triaging ...

**Comment by jd-campbell** [comment]
@adf-ncgr @cann0010 - Can this issue be closed?

**Comment by cann0010** [comment]
Yes. Closing.
